### ISSUE TITLE
Enums are not generated

### ISSUE THREAD

**Issue by Aresak** [Aresak/Interfacify#2]
I have to manually add enum field to the class.
The [Intefacify] attribute doesn't generate it.

Workaround:
```csharp
[Interfacify]
public partial class MyClass : IMyInterface
{
    // Implemented manually
    public MyEnum SomeField { get; set; }
}
```

**Comment by Aresak** [comment]
Additional types that are not implemented: `DateTime`, `Guid`

**Comment by Aresak** [comment]
Couldn't reproduce now, I need more details.
Test commit is in 42615bca85a69ca2274d91cf3a12d84bfcf629d3.

**Comment by TomasMalcanek** [comment]
I think the problem is when the enum lies in a different namespace.
The generated code doesn't have usings. That's why even DateTime and Guid isn't working, because they lie in the System namespace.
Same problem should exist if the generated code references another class that is not a primitive type.
